import gradio as gr


def create_app(self, inputs, prompt, streamer, _run_immediately):
    with gr.Blocks() as app:
        for input in inputs:
            input.render()

        prompt_box = gr.Textbox(label="Prompt", value=prompt)
        run_button = gr.Button("Run", variant="primary")

        @gr.on(
            triggers=[app.load] + [input.change for input in inputs],
            inputs=inputs,
            outputs=[prompt_box],
            trigger_mode="always_last",
        )
        def construct_prompt(*input_values):
            return prompt.format(*input_values)

        chat_log = gr.Chatbot(
            label="Log",
            type="messages",
            group_consecutive_messages=False,
            visible=False,
        )

        run_triggers = [run_button.click]
        if _run_immediately:
            run_triggers.append(app.load)

        @gr.on(
            triggers=run_triggers,
            inputs=[prompt_box],
            outputs=[run_button, results_tab],
        )
        def run_flow(prompt):
            yield {run_button: gr.Button(visible=False)}
            log = []
            for step in streamer(prompt):
                if isinstance(step, str):
                    log.append(gr.ChatMessage(content=step, role="assistant"))
                elif isinstance(step, gr.ChatMessage):
                    log.append(step)
                else:
                    raise ValueError(
                        f"Cannot handle type: {type(step)} generated by streamer function."
                    )
                yield {chat_log: log}

    return app
